import {
  BUN_TRAILER,
  BUN_VERSION_MATCH,
  BUN_VERSION_MATCH_OLD,
  BUNFS_ROOT,
  BUNFS_ROOT_OLD,
} from "./constants";

export interface BundledFile {
  path: string;
  contents: ArrayBuffer;
  sourcemap?: {
    version: 3;
    file: string;
    debugId?: string;
    mappings: string;
    sources: string[];
  };
}

const corruptionMessage =
  ". Either the binary is corrupted or it's not an executable file generated by `bun build --compile`.";

export class InvalidExecutableError extends Error {
  constructor(msg = "Invalid executable") {
    super(msg + corruptionMessage);
    this.name = "InvalidExecutableError";
  }
}

export class InvalidTrailerError extends InvalidExecutableError {
  constructor() {
    super("Invalid executable trailer");
    this.name = "InvalidTrailerError";
  }
}

export class TotalByteCountMismatchError extends InvalidExecutableError {
  constructor() {
    super("Executable byte count mismatch");
    this.name = "TotalByteCountMismatchError";
  }
}

export class VersionNotFoundError extends InvalidExecutableError {
  constructor() {
    super("Version not found in executable");
    this.name = "VersionNotFoundError";
  }
}

export interface ExtractBundledFilesOptions {
  normaliseEntrypointFileName?: boolean;
}

interface ModuleGraphLayout {
  byteCount: number;
  modulesPtrOffset: number;
  modulesPtrLength: number;
  entryPointId: number;
  structSize: number;
  modulesStart: number;
}

const OFFSET_STRUCT_SIZES = [32, 24] as const;

function readModuleGraphLayout(compiledBinaryData: DataView): ModuleGraphLayout {
  const totalLength = compiledBinaryData.byteLength;
  if (totalLength <= BUN_TRAILER.length + 8 + OFFSET_STRUCT_SIZES[OFFSET_STRUCT_SIZES.length - 1]) {
    return {
      byteCount: 0,
      modulesPtrOffset: 0,
      modulesPtrLength: 0,
      entryPointId: 0,
      structSize: OFFSET_STRUCT_SIZES[0],
      modulesStart: 0,
    };
  }

  for (const structSize of OFFSET_STRUCT_SIZES) {
    const metadataOverhead = BUN_TRAILER.length + 8 + structSize;
    if (totalLength < metadataOverhead) {
      continue;
    }

    const offsetsStart = totalLength - metadataOverhead;
    const byteCountBig = compiledBinaryData.getBigUint64(offsetsStart, true);
    if (byteCountBig === 0n) {
      continue;
    }
    if (byteCountBig > BigInt(Number.MAX_SAFE_INTEGER)) {
      continue;
    }
    const byteCount = Number(byteCountBig);

    const modulesPtrOffset = compiledBinaryData.getUint32(offsetsStart + 8, true);
    const modulesPtrLength = compiledBinaryData.getUint32(offsetsStart + 12, true);
    const entryPointId = compiledBinaryData.getUint32(offsetsStart + 16, true);

    const modulesStart = totalLength - (byteCount + metadataOverhead);
    const availableBytes = totalLength - metadataOverhead;
    if (byteCount > availableBytes || modulesPtrOffset + modulesPtrLength > byteCount) {
      continue;
    }

    return {
      byteCount,
      modulesPtrOffset,
      modulesPtrLength,
      entryPointId,
      structSize,
      modulesStart,
    };
  }

  throw new InvalidExecutableError("Invalid module graph offsets in executable");
}

export function extractBundledFiles(
  compiledBinaryData: DataView | ArrayBuffer,
  options: ExtractBundledFilesOptions = {},
) {
  options = {
    normaliseEntrypointFileName: true,
    ...options,
  };

  if (compiledBinaryData instanceof ArrayBuffer) {
    compiledBinaryData = new DataView(compiledBinaryData);
  }

  const decoder = new TextDecoder();

  const trailer = decoder.decode(
    compiledBinaryData.buffer.slice(
      compiledBinaryData.byteLength - 8 - BUN_TRAILER.length,
      compiledBinaryData.byteLength - 8,
    ),
  );
  if (trailer !== BUN_TRAILER) {
    throw new InvalidTrailerError();
  }

  const totalByteCount = compiledBinaryData.getBigUint64(
    compiledBinaryData.byteLength - 8,
    true,
  );
  if (totalByteCount !== BigInt(compiledBinaryData.byteLength)) {
    throw new TotalByteCountMismatchError();
  }

  const layout = readModuleGraphLayout(compiledBinaryData);
  const { entryPointId: entrypointId, modulesPtrOffset, modulesPtrLength, modulesStart } = layout;

  const modulesData = new Uint8Array(
    compiledBinaryData.buffer,
    modulesStart,
    modulesPtrOffset,
  );
  const validatePointer = (offset: number, length: number, label: string) => {
    if (offset + length > modulesPtrOffset) {
      throw new InvalidExecutableError(
        `Invalid ${label} pointer in executable`,
      );
    }
  };

  const slicePointer = (offset: number, length: number) =>
    modulesData.subarray(offset, offset + length);

  const decodePointerString = (offset: number, length: number) =>
    decoder
      .decode(slicePointer(offset, length))
      .replace(/\0+$/, "");
  const modulesMetadataStart = modulesStart + modulesPtrOffset;

  const metadataChunkCandidates = [36, 32, 28] as const;
  const modulesMetadataChunkSize =
    metadataChunkCandidates.find((size) => size !== 0 && modulesPtrLength % size === 0) ??
    metadataChunkCandidates[0];

  const bundledFiles: BundledFile[] = [];
  const moduleCount = Math.trunc(modulesPtrLength / modulesMetadataChunkSize);

  for (let i = 0; i < moduleCount; i++) {
    const modulesMetadataOffset = modulesMetadataStart + i * modulesMetadataChunkSize;
    const pathOffset = compiledBinaryData.getUint32(modulesMetadataOffset, true);
    const pathLength = compiledBinaryData.getUint32(modulesMetadataOffset + 4, true);
    const contentsOffset = compiledBinaryData.getUint32(modulesMetadataOffset + 8, true);
    const contentsLength = compiledBinaryData.getUint32(modulesMetadataOffset + 12, true);
    const sourcemapOffset = compiledBinaryData.getUint32(
      modulesMetadataOffset + 16,
      true,
    );
    const sourcemapLength = compiledBinaryData.getUint32(
      modulesMetadataOffset + 20,
      true,
    );
    const isEntrypoint = i === entrypointId;

    validatePointer(pathOffset, pathLength, "path");
    let path = decodePointerString(pathOffset, pathLength);
    if (options.normaliseEntrypointFileName && isEntrypoint) {
      path = path.replace(/\/[^\/\\]+$/, "/index.js");
    }
    path = removeBunfsRootFromPath(path);
    if (path[0] !== "/") {
      throw new InvalidExecutableError("Invalid path in bundled file in executable");
    }
    path = removeLeadingSlash(path);

    validatePointer(contentsOffset, contentsLength, "contents");
    const contentsStart = contentsOffset;
    const contentsEnd = contentsStart + contentsLength;
    const contents = modulesData.slice(contentsStart, contentsEnd).buffer;

    let sourcemap: BundledFile["sourcemap"];
    if (sourcemapLength) {
      validatePointer(sourcemapOffset, sourcemapLength, "sourcemap");
      const sourcemapBase = sourcemapOffset;
      const sourcemapHeaderOffset = modulesStart + sourcemapBase;
      const headerFirstByte = compiledBinaryData.getUint8(sourcemapHeaderOffset);
      const headerShift = headerFirstByte === 0 ? 1 : 0;
      const headerBase = sourcemapHeaderOffset + headerShift;

      const sourcemapSourcesCount = compiledBinaryData.getUint32(
        headerBase,
        true,
      );
      const sourcemapMappingsLength = compiledBinaryData.getUint32(
        headerBase + 4,
        true,
      );

      const pathPointerBase = headerBase + 8;

      if (sourcemapSourcesCount || sourcemapMappingsLength) {
        const mappingsStart =
          sourcemapBase + headerShift + 8 + sourcemapSourcesCount * 16;
        const mappingsEnd = mappingsStart + sourcemapMappingsLength;
        if (mappingsEnd > sourcemapBase + sourcemapLength) {
          throw new InvalidExecutableError("Invalid sourcemap data in executable");
        }

        const contentsBytes = slicePointer(contentsStart, contentsLength);
        const contentsEndSliceStart = Math.max(
          contentsBytes.length - 49,
          0,
        );
        const contentsEndData = decoder.decode(
          contentsBytes.subarray(contentsEndSliceStart),
        );
        const debugId = contentsEndData.match(/^\/\/# debugId=([a-fA-F0-9-]{12,})$/m)?.[1];

        sourcemap = {
          version: 3,
          file: path,
          debugId,
          mappings: decoder.decode(
            slicePointer(mappingsStart, sourcemapMappingsLength),
          ),
          sources: [],
        };

        let sourceStart = mappingsEnd;
        for (let j = 0; j < sourcemapSourcesCount; j++) {
          const sourcemapSourceLength = compiledBinaryData.getUint32(
            pathPointerBase + j * 8 + 4,
            true,
          );

          validatePointer(sourceStart, sourcemapSourceLength, "sourcemap source");

          sourcemap.sources.push(
            decodePointerString(sourceStart, sourcemapSourceLength),
          );

          sourceStart += sourcemapSourceLength;
        }
      }
    }

    const bundledFile: BundledFile = {
      path,
      contents,
      sourcemap,
    };

    if (isEntrypoint) {
      bundledFiles.unshift(bundledFile);
    } else {
      bundledFiles.push(bundledFile);
    }
  }

  return bundledFiles;
}

function getModulesStart(compiledBinaryData: DataView) {
  try {
    return readModuleGraphLayout(compiledBinaryData).modulesStart;
  } catch (e) {
    if (e instanceof InvalidExecutableError) {
      return compiledBinaryData.byteLength;
    }
    throw e;
  }
}

function removeBunfsRootFromPath(path: string) {
  if (path.startsWith(BUNFS_ROOT)) {
    return path.slice(BUNFS_ROOT.length);
  }
  if (path.startsWith(BUNFS_ROOT_OLD)) {
    return path.slice(BUNFS_ROOT_OLD.length);
  }
  throw new Error(`Path does not start with Bun-fs root: ${path}`);
}

export function removeLeadingSlash(path: string) {
  return path.replace(/^\/?(?:\.\/)?/, "");
}

export interface BunVersion {
  version: string;
  revision: string;
  newFormat?: boolean;
}

function getExecutableVersionNew(data: Uint8Array, modulesStart: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= modulesStart) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(27, versionIndex + BUN_VERSION_MATCH.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)$/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

function getExecutableVersionOld(data: Uint8Array, modulesStart: number): BunVersion {
  const versionIndex = data.findIndex((_, index) => {
    if (index >= modulesStart) {
      return false;
    }

    for (let i = 0; i < BUN_VERSION_MATCH_OLD.length; i++) {
      if (data[index + i] !== BUN_VERSION_MATCH_OLD.charCodeAt(i)) {
        return false;
      }
    }

    return true;
  });

  if (versionIndex === -1) {
    throw new VersionNotFoundError();
  }

  const versionEndIndex = data.indexOf(58, versionIndex + BUN_VERSION_MATCH_OLD.length);

  if (versionEndIndex <= 0) {
    throw new VersionNotFoundError();
  }

  const decoder = new TextDecoder();
  const versionString = decoder.decode(
    data.slice(versionIndex + BUN_VERSION_MATCH_OLD.length, versionEndIndex),
  );

  const [, version, revision] = versionString.match(/^(.+) \((.+)\)/) ?? [];

  if (!version) {
    throw new VersionNotFoundError();
  }

  return {
    version,
    revision,
  };
}

export function getExecutableVersion(data: Uint8Array | ArrayBuffer): BunVersion {
  if (data instanceof ArrayBuffer) {
    data = new Uint8Array(data);
  }

  const modulesStart = getModulesStart(new DataView(data.buffer));

  try {
    return { ...getExecutableVersionNew(data, modulesStart), newFormat: true };
  } catch (e) {
    if (e instanceof VersionNotFoundError) {
      return { ...getExecutableVersionOld(data, modulesStart), newFormat: false };
    }

    throw e;
  }
}
